engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app_client/**
  - app_server/**
  - "app.js"
exclude_paths:
- "test-client-e2e/"
- "test-client-e2e-angular1-deprecated/"
- "test-server-integration/"
- "test-server-unit/"
- "spec"
- "docs"
- "bin"
- "**/*.log"
- "app_client/e2e/"
- "app_client/config/"
- "app_client/assets/"
- "app_client/src/typings.d.ts"
- "app_client/src/app/**/*.spec.ts"
