engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  nodesecurity:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - app_client/**
  - app_server/**
  - "**.css"
  - "**.scss"
  - "app.js"
exclude_paths:
- "test-client-e2e/"
- "test-client-e2e-angular1-deprecated/"
- "test-server-integration/"
- "test-server-unit/"
- "spec"
- "docs"
- "bin"
- "**/*.log"
- "app_client/e2e/"
- "app_client/config/"
- "app_client/assets/"
- "app_client/src/typings.d.ts"
- "app_client/src/app/**/*.spec.ts"
