language: node_js
node_js:
  - "6.1"
before_script:
  - npm install -g mocha
  - npm install -g nodemon
  - npm install -g gulp@github:gulpjs/gulp#4.0
  - npm install -g istanbul
sudo: required
script:
  - mocha test-server-integration/
  - mocha test-server-unit/3dparty-passport-test.js
  - mocha test-server-unit/auth-experimental-collapse-db-test.js
  - mocha test-server-unit/auth-util-test.js
  - mocha test-server-unit/users-test.js
  - mocha test-server-unit/util-test.js
services:
  - mongodb
  - redis-server
