language: node_js
node_js:
  - "7" # latest nodejs 7
  - "7.0"
  - "6" # latest nodejs 6
  - "6.1"
  - "6.0"
env:
  - NODE_ENV=test CI=yes
before_script:
  - bash travisci/before_script.sh
sudo: required
script:
  - bash travisci/travis_script.sh
#services:
#  - mongodb
#  - redis-server
addons:
  code_climate:
    repo_token: 8992777c415fd321e37092b0c44837f6d0e9a5647c8369854e8e32e0a47e3850
cache: # enable caching
  bundler: true
  directories:
  - node_modules # NPM packages
