# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml
# This file: cloned from https://github.com/gruntjs/grunt/blob/master/appveyor.yml

# Build version format
version: "{build}"

environment:
  nodejs_version: "Stable"
  NODE_ENV: test
  CI: yes
  APPVEYOR: yes

build: off

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g karma-cli
  - npm install -g webpack@2.2.0-rc.2
  - npm install -g typescript@2.0.10
  - npm install -g typings
  - npm install -g remap-istanbul
  - npm install -g webdriver-manager
  - npm install -g protractor
  - npm install -g codeclimate-test-reporter
  - npm install -g istanbul
  - npm install


test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm --version # PowerShell" # Pass comment to PS for easier debugging
  # - npm run tests.all && npm run build.prod.exp
  # - npm run buildDev
  # - npm run build
  - npm test

#notifications:
 # - provider: Webhook
#    url: https://webhooks.gitter.im/e/cfd8ce5ddee6f3a0b0c9
#    on_build_success: false
#    on_build_failure: true
#    on_build_status_changed: true

cache: node_modules -> package.json